SELECT * FROM customer;

-- Q1. What is the total revenue generated by male vs female customers ?
SELECT 
	gender, 
    SUM(purchase_amount)
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the avg purchase amount and their total count ?
SELECT 
	customer_id,
    purchase_amount,
    COUNT(*) OVER() AS count
FROM customer
WHERE discount_applied = 'Yes' 
	AND purchase_amount >= (
		SELECT AVG(purchase_amount)
        FROM customer
	);


-- Q3. Which are the top 5 products with highest average review rating ?
SELECT 
	item_purchased, 
	ROUND(AVG(review_rating),2) as avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;


-- Q4. Compare the average purhase amounts of all the shipping types ?
SELECT shipping_type,
	ROUND(AVG(purchase_amount),2) as avg_purchase_amount
FROM customer
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC;


-- Q5. Do subscribed customers spend more? Comapre avg spend and total revenue between subscribers and non-subscribers.
 SELECT 
	subscription_status,
    COUNT(customer_id) as total_customers,
    ROUND(AVG(purchase_amount),2) as avg_spend, 
    ROUND(SUM(purchase_amount),2) as total_spend
FROM customer
GROUP BY subscription_status;
	

-- Q6. Which 5 products have the highest percentage of purchase when discount applied? (helps to find which products heavily rely on discount to get sold)
SELECT
	item_purchased as product_name,
    -- (discounted purchases per product / total purchases per product) * 100
    ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100 / COUNT(*), 2) AS discount_purchase_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_purchase_percentage DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type_CTE as(
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) as 'Number of customers'
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the Top 3 most purchased products within each category ? 
WITH most_purchased_CTE AS
(
	SELECT 
		category,
        item_purchased,
		COUNT(customer_id) as total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
	FROM customer
    GROUP BY category, item_purchased
)
SELECT 
	item_rank, category, item_purchased, total_orders
FROM most_purchased_CTE
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
SELECT 
	subscription_status,
    COUNT(customer_id) as repeat_customers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is revenue contribution of each age group ?
SELECT 
	age_group, 
    SUM(purchase_amount) as revenue_contribution
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution DESC;


    



